### ISSUE TITLE
Why two Proxies instead of one? 

### ISSUE THREAD

**Issue by escamoteur** [jaumard/proxy_layout#1]
Hi,
I was just wondering if it wouldn't be better to have one proxy that offers all 4 combinations of orientation and size because if I already care for different sizes I probably also want to handle orientation.

**Comment by jaumard** [comment]
Hello @escamoteur ! I was thinking about this just yesterday ! Because in my app I generally use both app ^^
So my idea was to keep the current proxies as they are because you always don't care about tablets or landscape but I'm 100% to add a new one that merge both of them :) 
I think it's a great idea.
